import os,re
d='data/event-guides'
ids=sorted(f[:-3] for f in os.listdir(d) if f.endswith('.ts') and f!='index.ts')
def var(i): return 'g_'+re.sub(r'\W','_',i)
out='// Generated by scripts_gen_guides_index.py: one file per event, listed here.\nimport type { EventGuide } from "@/types/eventGuides";\n'
for i in ids: out+=f'import {var(i)} from "./{i}";\n'
out+='\nexport const eventGuides: EventGuide[] = [\n'+''.join(f'  {var(i)},\n' for i in ids)+'];\n'
out+='''
export function getEventGuide(eventId: string): EventGuide | undefined {
  return eventGuides.find((g) => g.eventId === eventId);
}
'''
open(d+'/index.ts','w').write(out)
print(len(ids),'guides')
