// Generated by scripts_gen_guides_index.py: one file per event, listed here.
import type { EventGuide } from "@/types/eventGuides";
import g_agent_conference_2027 from "./agent-conference-2027";
import g_agntcon_mcpcon_na_2026 from "./agntcon-mcpcon-na-2026";
import g_ai_summit_london_2027 from "./ai-summit-london-2027";
import g_ai_summit_new_york_2026 from "./ai-summit-new-york-2026";
import g_bitcoin_2027 from "./bitcoin-2027";
import g_bitcoin_mena_2026 from "./bitcoin-mena-2026";
import g_blockchain_life_2026 from "./blockchain-life-2026";
import g_ces_2027 from "./ces-2027";
import g_consensus_miami_2027 from "./consensus-miami-2027";
import g_devcon_8_mumbai_2026 from "./devcon-8-mumbai-2026";
import g_digital_asset_summit_london_2026 from "./digital-asset-summit-london-2026";
import g_ethcc_10_2027 from "./ethcc-10-2027";
import g_gitex_global_2026 from "./gitex-global-2026";
import g_hong_kong_fintech_week_2026 from "./hong-kong-fintech-week-2026";
import g_humanx_2027 from "./humanx-2027";
import g_intelligence_disrupt_2027 from "./intelligence-disrupt-2027";
import g_mining_disrupt_2027 from "./mining-disrupt-2027";
import g_money2020_usa_2026 from "./money2020-usa-2026";
import g_money2020_usa_2027 from "./money2020-usa-2027";
import g_neurips_2026 from "./neurips-2026";
import g_nvidia_gtc_2027 from "./nvidia-gtc-2027";
import g_signal_week_paris_2027 from "./signal-week-paris-2027";
import g_singapore_fintech_festival_2026 from "./singapore-fintech-festival-2026";
import g_smartcon_2026 from "./smartcon-2026";
import g_solana_breakpoint_2026 from "./solana-breakpoint-2026";
import g_superai_singapore_2027 from "./superai-singapore-2027";
import g_token2049_dubai_2027 from "./token2049-dubai-2027";
import g_token2049_singapore_2026 from "./token2049-singapore-2026";
import g_web_summit_2026 from "./web-summit-2026";
import g_web_summit_qatar_2027 from "./web-summit-qatar-2027";
import g_webx_tokyo_2027 from "./webx-tokyo-2027";
import g_world_summit_ai_2026 from "./world-summit-ai-2026";

export const eventGuides: EventGuide[] = [
  g_agent_conference_2027,
  g_agntcon_mcpcon_na_2026,
  g_ai_summit_london_2027,
  g_ai_summit_new_york_2026,
  g_bitcoin_2027,
  g_bitcoin_mena_2026,
  g_blockchain_life_2026,
  g_ces_2027,
  g_consensus_miami_2027,
  g_devcon_8_mumbai_2026,
  g_digital_asset_summit_london_2026,
  g_ethcc_10_2027,
  g_gitex_global_2026,
  g_hong_kong_fintech_week_2026,
  g_humanx_2027,
  g_intelligence_disrupt_2027,
  g_mining_disrupt_2027,
  g_money2020_usa_2026,
  g_money2020_usa_2027,
  g_neurips_2026,
  g_nvidia_gtc_2027,
  g_signal_week_paris_2027,
  g_singapore_fintech_festival_2026,
  g_smartcon_2026,
  g_solana_breakpoint_2026,
  g_superai_singapore_2027,
  g_token2049_dubai_2027,
  g_token2049_singapore_2026,
  g_web_summit_2026,
  g_web_summit_qatar_2027,
  g_webx_tokyo_2027,
  g_world_summit_ai_2026,
];

export function getEventGuide(eventId: string): EventGuide | undefined {
  return eventGuides.find((g) => g.eventId === eventId);
}
